### ISSUE TITLE
Autogenerated names are interpreted as phone numbers in Safari for iOS

### ISSUE THREAD

**Issue by jacobslusser** [Tanq16/local-content-share#4]
Great project!

I noticed that when I share text, there is an autogenerated share name (which can be renamed manually) that will get interpreted as a phone number on Safari for iOS. This led to some confusion because I initially attempted to click the link instead of the view text button. 

One solution would be to change the format of the autogenerated names to alpha-numeric-based instead of date-based, but the even easier option would be to add a `meta` tag to disable phone number behavior in Safari for iOS.

Some relevant documentation:
- [User id detected as phone number on Mobile Safari](https://meta.stackoverflow.com/questions/331783/user-id-detected-as-phone-number-on-mobile-safari)
- [Stop Safari-Mobile from converting 7 digits numbers into "tel" format](https://meta.stackexchange.com/questions/243640/stop-safari-mobile-from-converting-7-digits-numbers-into-tel-format)
- [Apple URL Scheme Reference](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html)

![file-IMG_5631](https://github.com/user-attachments/assets/b29b11cd-5135-4043-8d54-1868f817f578)
![file-IMG_5632](https://github.com/user-attachments/assets/7b267aaa-6323-4914-8169-47bb3151a507)
![file-IMG_5633](https://github.com/user-attachments/assets/c3ef78a1-9367-4828-b920-9782aed2a850)

**Comment by Tanq16** [comment]
Thank you @jacobslusser ! These are good catches, I'll implement a fix later today.
