### ISSUE TITLE
Naming and save-prompts when downloading files

### ISSUE THREAD

**Issue by jacobslusser** [Tanq16/local-content-share#5]
A minor pet-peeve about downloading shared files is the behavior and the naming.

**Download**
The download icon always suggests to me that I will get a download (i.e. be prompted to save), but what happens here is that it opens the file for viewing. I would suggest adding a second icon/button that is the eye icon next to the download icon. The eye/view icon will result in the behavior as it currently is today, while the download icon will result in a save-prompt for the user. Off the top of my head, I think this save-behavior can be accomplished with the [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header.

**Naming**
Related to the download/viewing behavior is the name of the files. On the filesystem they get renamed to `file-<original>` which is perfectly fine, but it would be nice if the original could be round-tripped completely, independent of the naming convention on the server. Again, I believe this can be accomplished very easily without changing the naming convention on the server by using the `Content-Disposition` header, independent of the file name on disk or in the URL.

**Comment by Tanq16** [comment]
Good catch @jacobslusser , I've been meaning to do away with the `file-` and `text-` prefixes and instead bucketing into directories. That should fix the naming, but will be a breaking change so i'll delay this fix a bit.

Preview vs. download is a good point - it's mainly the web browser's default but yes, i should be able to override that.

**Comment by Tanq16** [comment]
Thanks for the suggestions and contribution, this is fixed and incorporated in #6
Also, files are now stored in subfolders now.

You should be able to pull the new image directly as it is backwards compatible and will migrate to new structure on first run (everything that had the `file-` and `text-` prefixes).
