### ISSUE TITLE
An iOS Share Shortcut

### ISSUE THREAD

**Issue by jacobslusser** [Tanq16/local-content-share#7]
Thanks again @Tanq16 for this project. This is not an issue, but Discussions is not enabled for this project, so putting it here. I slapped together a simple shortcut in iOS that will send items to local-content-share. If anyone else is interested, here you go. 

https://www.icloud.com/shortcuts/01a27ada571c478b9f0e205e49e56f8b

Actions are pretty simple:
1. Get content shared or clipboard
2. POST to the `/submit` path of where you are hosting local-content-share. e.g. replace `example.com` with your custom endpoint. (NOTE: it is not obvious from the screenshot, but the `file` variable is set to the shortcut input, i.e. file).

It's configured by default to show on the "share sheet" so any item in iOS that has a share button will have this option in the menu.

![shortcut](https://github.com/user-attachments/assets/6e140b07-0a7d-4dba-a452-c0fe47772e8b)

**Comment by Tanq16** [comment]
this is a nice idea, thank you!! I enabled discussions and moved this there.
